### PR TITLE
Updated and Improved Discordify

### PR DESCRIPTION
**Pull request by MasicoreLord**

### CODE REVIEW

**Comment by MasicoreLord** [comment]
The main.css file appearing to have everything changed, is because I did minified it, the source was moved to main.source.css so the full sourcecode is still available.

@nirewen

**Comment by MasicoreLord** [comment]
It's been 2 weeks and no response or merge happened, I'll just close this PR and cancel the patched theme project.  If you are actually still interested, you can contact me, and I'll start this back up.

**Comment by MasicoreLord** [comment]
Discord had wildly speedy breaking updates during alot of those days, and at the same time it felt like it was taking forever to see any kind of response, that's why I prematurely closed it @nirewen

**Comment by MasicoreLord** [comment]
Almost all those later pull request were to deal w/ those updates Discord pushed down rapidly.

**Comment by nirewen** [comment]
Sad...

**Pull request closed without merging**
